; ========================================================
; DualSenser - Arquivo de Configuracao
; ========================================================

[Settings]
; Se true, exibe no log toda atividade do controle (botoes, analogicos, gatilhos e trackpad)
ShowControllerActivity=true

[Network]
; Porta do servidor HTTP e WebSockets para comunicacao com o app Android
HttpPort=5005
; Habilita a emissao de beacons UDP na rede local para auto-descoberta
EnableUdpBeacon=true
; Porta de broadcast UDP
UdpBeaconPort=54321
; Intervalo em segundos entre cada transmissao de beacon de descoberta
UdpBeaconIntervalSeconds=3
