; ========================================================
; DualSenser - Arquivo de Configuracao
; ========================================================
[Settings]
; Se true, exibe no log toda atividade do controle (botoes, analogicos, gatilhos e trackpad)
ShowControllerActivity=true
